// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void OpaOn_Animation( lv_obj_t *TargetObject, int delay);
void OpaOff_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_S1_Scan
void ui_S1_Scan_screen_init(void);
lv_obj_t *ui_S1_Scan;
lv_obj_t *ui_UI_BG_S1;
lv_obj_t *ui_BTN_Menu_Scan_S1;
void ui_event_BTN_Menu_Move_S1( lv_event_t * e);
lv_obj_t *ui_BTN_Menu_Move_S1;
void ui_event_BTN_Menu_Settings_S1( lv_event_t * e);
lv_obj_t *ui_BTN_Menu_Settings_S1;
lv_obj_t *ui_StatusBar_S1;
lv_obj_t *ui_ICON_PC_Online_S1;
lv_obj_t *ui_StatusBarLbl_S1;
lv_obj_t *ui_Progress_Panel;
void ui_event_PROG_BAR_Scan_Progress( lv_event_t * e);
lv_obj_t *ui_PROG_BAR_Scan_Progress;
lv_obj_t *ui_TopFrame;
lv_obj_t *ui_LBL_Progress_Percent;
lv_obj_t *ui_Scan_Time_Panel;
lv_obj_t *ui_LBL_Title_Scan_Time;
lv_obj_t *ui_LBL_Title_Remaining_Time;
lv_obj_t *ui_Separator;
lv_obj_t *ui_LBL_Scan_Time;
lv_obj_t *ui_LBL_Scan_Time1;
lv_obj_t *ui_ICON_Scan_Time_Clock;
lv_obj_t *ui_ICON_Remaining_Time_Clock;
lv_obj_t *ui_Scanner_Param_Panel;
lv_obj_t *ui_LBL_Title_Average_Current;
lv_obj_t *ui_LBL_Title_Remaining_Time1;
lv_obj_t *ui_Separator1;
lv_obj_t *ui_LBL_Scan_Time2;
lv_obj_t *ui_LBL_Scan_Time3;
lv_obj_t *ui_ICON_Current;
lv_obj_t *ui_ICON_Temperature;
lv_obj_t *ui_Panel5;
void ui_event_BTN_Pause_Scan( lv_event_t * e);
lv_obj_t *ui_BTN_Pause_Scan;
lv_obj_t *ui_ICON_Pause;
void ui_event_BTN_Stop_Scan( lv_event_t * e);
lv_obj_t *ui_BTN_Stop_Scan;
lv_obj_t *ui_ICON_Stop;


// SCREEN: ui_S2_Move
void ui_S2_Move_screen_init(void);
lv_obj_t *ui_S2_Move;
lv_obj_t *ui_UI_BG_S2;
void ui_event_BTN_Menu_Scan_S2( lv_event_t * e);
lv_obj_t *ui_BTN_Menu_Scan_S2;
lv_obj_t *ui_BTN_Menu_Move_S2;
void ui_event_BTN_Menu_Settings_S2( lv_event_t * e);
lv_obj_t *ui_BTN_Menu_Settings_S2;
lv_obj_t *ui_StatusBar_S2;
lv_obj_t *ui_StatusBarLbl_S2;
lv_obj_t *ui_ICON_PC_Online_S2;
lv_obj_t *ui_MovePadsPanel;
lv_obj_t *ui_Move_Knob_Panel;
lv_obj_t *ui_MOVE_Knob_BG;
void ui_event_BTN_BCK_GLOW( lv_event_t * e);
lv_obj_t *ui_BTN_BCK_GLOW;
void ui_event_BTN_FWD_GLOW( lv_event_t * e);
lv_obj_t *ui_BTN_FWD_GLOW;
void ui_event_BTN_LEFT_GLOW( lv_event_t * e);
lv_obj_t *ui_BTN_LEFT_GLOW;
void ui_event_BTN_RIGHT_GLOW( lv_event_t * e);
lv_obj_t *ui_BTN_RIGHT_GLOW;
lv_obj_t *ui_MOVE_Knob_TOP;
lv_obj_t *ui_Arrow_FWD;
lv_obj_t *ui_Arrow_BCK;
lv_obj_t *ui_Arrow_LEFT;
lv_obj_t *ui_Arrow_RIGHT;
lv_obj_t *ui_Updown_Knob_Panel;
lv_obj_t *ui_UPDOWN_Knob_BG;
void ui_event_BTN_UP_GLOW( lv_event_t * e);
lv_obj_t *ui_BTN_UP_GLOW;
void ui_event_BTN_DOWN_GLOW( lv_event_t * e);
lv_obj_t *ui_BTN_DOWN_GLOW;
lv_obj_t *ui_UPDOWN_Knob;
lv_obj_t *ui_Arrow_UP;
lv_obj_t *ui_Arrow_DOWN;
lv_obj_t *ui_Panel_Step_Size;
void ui_event_SLIDER_Step_Size( lv_event_t * e);
lv_obj_t *ui_SLIDER_Step_Size;
lv_obj_t *ui_LBL_Step_Size;
lv_obj_t *ui_PositionPanel;
lv_obj_t *ui_LBL_Pos_Title;
lv_obj_t *ui_POS_Separator1;
lv_obj_t *ui_POS_Separator2;
lv_obj_t *ui_LBL_Title_Pos_X_;
lv_obj_t *ui_LBL_Title_Pos_Y_;
lv_obj_t *ui_LBL_Title_Pos_Z_;
lv_obj_t *ui_LBL_X_Pos;
lv_obj_t *ui_LBL_Y_Pos;
lv_obj_t *ui_LBL_Y_Pos1;
lv_obj_t *ui_Status_Panel;
lv_obj_t *ui_POS_Separator3;
lv_obj_t *ui_LBL_Title_Enabled;
lv_obj_t *ui_LED_Enabled;
lv_obj_t *ui_LBL_Title_Referenced;
lv_obj_t *ui_LED_Referenced;
lv_obj_t *ui_LBL_Title_Sanity;
lv_obj_t *ui_LED_Sanity;
void ui_event_BTN_Reset_Pos( lv_event_t * e);
lv_obj_t *ui_BTN_Reset_Pos;
lv_obj_t *ui_BTN_LBL_Reset_pos;
void ui_event_BTN_Reference( lv_event_t * e);
lv_obj_t *ui_BTN_Reference;
lv_obj_t *ui_BTN_LBL_Reference;
void ui_event_BTN_Halt( lv_event_t * e);
lv_obj_t *ui_BTN_Halt;
lv_obj_t *ui_BTN_LBL_Halt;
void ui_event_On_BTN_Panel( lv_event_t * e);
lv_obj_t *ui_On_BTN_Panel;
lv_obj_t *ui_BTN_Icon_Turn_ON;


// SCREEN: ui_S3_Settings
void ui_S3_Settings_screen_init(void);
lv_obj_t *ui_S3_Settings;
lv_obj_t *ui_UI_BG_S3;
void ui_event_BTN_Menu_Scan_S3( lv_event_t * e);
lv_obj_t *ui_BTN_Menu_Scan_S3;
void ui_event_BTN_Menu_Move_S3( lv_event_t * e);
lv_obj_t *ui_BTN_Menu_Move_S3;
lv_obj_t *ui_BTN_Menu_Settings_S3;
lv_obj_t *ui_StatusBar_S3;
lv_obj_t *ui_StatusBarLbl_S3;
lv_obj_t *ui_ICON_PC_Online_S3;
lv_obj_t *ui_General_Settings_Panel;
lv_obj_t *ui_SWITCH_Post_Shutdown;
lv_obj_t *ui_SWITCH_Light_LEDs;
lv_obj_t *ui_LBL_Title_Intern_Lights;
lv_obj_t *ui_LBL_Title_Post_Shutdown;
lv_obj_t *ui_General_Status_Panel;
lv_obj_t *ui_LBL_Title_Estop;
lv_obj_t *ui_LBL_Title_Door;
lv_obj_t *ui_LED_EStop;
lv_obj_t *ui_LED_Door;
lv_obj_t *ui_Instr_IP_Address_Panel;
void ui_event_TXT_IP_OCT4( lv_event_t * e);
lv_obj_t *ui_TXT_IP_OCT4;
void ui_event_TXT_IP_OCT3( lv_event_t * e);
lv_obj_t *ui_TXT_IP_OCT3;
void ui_event_TXT_IP_OCT2( lv_event_t * e);
lv_obj_t *ui_TXT_IP_OCT2;
void ui_event_TXT_IP_OCT1( lv_event_t * e);
lv_obj_t *ui_TXT_IP_OCT1;
lv_obj_t *ui_LBL_IP_Dot;
lv_obj_t *ui_LBL_IP_Dot1;
lv_obj_t *ui_LBL_IP_Dot2;
void ui_event_KEY_IP_Input( lv_event_t * e);
lv_obj_t *ui_KEY_IP_Input;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_icn_time_[2] = {&ui_img_icn_time_1_png, &ui_img_icn_time_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void OpaOn_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 10);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void OpaOff_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 266, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_BTN_Menu_Move_S1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_S2_Move, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_S2_Move_screen_init);
}
}
void ui_event_BTN_Menu_Settings_S1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_S3_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_S3_Settings_screen_init);
}
}
void ui_event_PROG_BAR_Scan_Progress( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_LBL_Progress_Percent, target, "", "%");
}
}
void ui_event_BTN_Pause_Scan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_ICON_Pause, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_ICON_Pause, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_BTN_Stop_Scan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_ICON_Stop, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_ICON_Stop, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      _ui_state_modify( ui_ICON_Stop, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_BTN_Menu_Scan_S2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_S1_Scan, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_S1_Scan_screen_init);
}
}
void ui_event_BTN_Menu_Settings_S2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_S3_Settings, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_S3_Settings_screen_init);
}
}
void ui_event_BTN_BCK_GLOW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_BTN_BCK_GLOW, 0);
      _ui_state_modify( ui_Arrow_BCK, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
      moveBackBtnPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_BTN_BCK_GLOW, 0);
      _ui_state_modify( ui_Arrow_BCK, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveBackBtnReleased( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_BTN_BCK_GLOW, 0);
      _ui_state_modify( ui_Arrow_BCK, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveBackBtnReleased( e );
}
}
void ui_event_BTN_FWD_GLOW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_BTN_FWD_GLOW, 0);
      _ui_state_modify( ui_Arrow_FWD, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
      moveFwdBtnPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_BTN_FWD_GLOW, 0);
      _ui_state_modify( ui_Arrow_FWD, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveFwdBtnReleased( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_BTN_FWD_GLOW, 0);
      _ui_state_modify( ui_Arrow_FWD, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveFwdBtnReleased( e );
}
}
void ui_event_BTN_LEFT_GLOW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_BTN_LEFT_GLOW, 0);
      _ui_state_modify( ui_Arrow_LEFT, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
      moveLeftBtnPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_BTN_LEFT_GLOW, 0);
      _ui_state_modify( ui_Arrow_LEFT, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveLeftBtnReleased( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_BTN_LEFT_GLOW, 0);
      _ui_state_modify( ui_Arrow_LEFT, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveLeftBtnReleased( e );
}
}
void ui_event_BTN_RIGHT_GLOW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_BTN_RIGHT_GLOW, 0);
      _ui_state_modify( ui_Arrow_RIGHT, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
      moveRightBtnPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_BTN_RIGHT_GLOW, 0);
      _ui_state_modify( ui_Arrow_RIGHT, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveRightBtnReleased( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_BTN_RIGHT_GLOW, 0);
      _ui_state_modify( ui_Arrow_RIGHT, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveRightBtnReleased( e );
}
}
void ui_event_BTN_UP_GLOW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_BTN_UP_GLOW, 0);
      _ui_state_modify( ui_Arrow_UP, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
      moveUpBtnPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_BTN_UP_GLOW, 0);
      _ui_state_modify( ui_Arrow_UP, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveUpBtnReleased( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_BTN_UP_GLOW, 0);
      _ui_state_modify( ui_Arrow_UP, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveUpBtnReleased( e );
}
}
void ui_event_BTN_DOWN_GLOW( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      OpaOn_Animation(ui_BTN_DOWN_GLOW, 0);
      _ui_state_modify( ui_Arrow_DOWN, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
      moveDownBtnPressed( e );
}
if ( event_code == LV_EVENT_RELEASED) {
      OpaOff_Animation(ui_BTN_DOWN_GLOW, 0);
      _ui_state_modify( ui_Arrow_DOWN, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveDownBtnReleased( e );
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      OpaOff_Animation(ui_BTN_DOWN_GLOW, 0);
      _ui_state_modify( ui_Arrow_DOWN, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
      moveDownBtnReleased( e );
}
}
void ui_event_SLIDER_Step_Size( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_LBL_Step_Size, target, "Step = ", " mm");
}
}
void ui_event_BTN_Reset_Pos( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_BTN_LBL_Reset_pos, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_BTN_LBL_Reset_pos, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      _ui_state_modify( ui_BTN_LBL_Reset_pos, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_BTN_Reference( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_BTN_LBL_Reference, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_BTN_LBL_Reference, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      _ui_state_modify( ui_BTN_LBL_Reference, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_BTN_Halt( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_BTN_LBL_Halt, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_BTN_LBL_Halt, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_PRESS_LOST) {
      _ui_state_modify( ui_BTN_LBL_Halt, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_On_BTN_Panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_BTN_Icon_Turn_ON, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_BTN_Icon_Turn_ON, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_BTN_Menu_Scan_S3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_S1_Scan, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_S1_Scan_screen_init);
}
}
void ui_event_BTN_Menu_Move_S3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_S2_Move, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_S2_Move_screen_init);
}
}
void ui_event_TXT_IP_OCT4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KEY_IP_Input,  ui_TXT_IP_OCT4);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TXT_IP_OCT3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KEY_IP_Input,  ui_TXT_IP_OCT3);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TXT_IP_OCT2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KEY_IP_Input,  ui_TXT_IP_OCT2);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TXT_IP_OCT1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KEY_IP_Input,  ui_TXT_IP_OCT1);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_KEY_IP_Input( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_S1_Scan_screen_init();
ui_S2_Move_screen_init();
ui_S3_Settings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_S1_Scan);
}
