// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void OpaOn_Animation( lv_obj_t *TargetObject, int delay);
void OpaOff_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_S1_Scan
void ui_S1_Scan_screen_init(void);
extern lv_obj_t *ui_S1_Scan;
extern lv_obj_t *ui_UI_BG_S1;
extern lv_obj_t *ui_BTN_Menu_Scan_S1;
void ui_event_BTN_Menu_Move_S1( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Move_S1;
void ui_event_BTN_Menu_Settings_S1( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Settings_S1;
extern lv_obj_t *ui_StatusBar_S1;
extern lv_obj_t *ui_ICON_PC_Online_S1;
extern lv_obj_t *ui_StatusBarLbl_S1;
extern lv_obj_t *ui_Progress_Panel;
void ui_event_PROG_BAR_Scan_Progress( lv_event_t * e);
extern lv_obj_t *ui_PROG_BAR_Scan_Progress;
extern lv_obj_t *ui_TopFrame;
extern lv_obj_t *ui_LBL_Progress_Percent;
extern lv_obj_t *ui_Scan_Time_Panel;
extern lv_obj_t *ui_LBL_Title_Scan_Time;
extern lv_obj_t *ui_LBL_Title_Remaining_Time;
extern lv_obj_t *ui_Separator;
extern lv_obj_t *ui_LBL_Scan_Time;
extern lv_obj_t *ui_LBL_Scan_Time1;
extern lv_obj_t *ui_ICON_Scan_Time_Clock;
extern lv_obj_t *ui_ICON_Remaining_Time_Clock;
extern lv_obj_t *ui_Scanner_Param_Panel;
extern lv_obj_t *ui_LBL_Title_Average_Current;
extern lv_obj_t *ui_LBL_Title_Remaining_Time1;
extern lv_obj_t *ui_Separator1;
extern lv_obj_t *ui_LBL_Scan_Time2;
extern lv_obj_t *ui_LBL_Scan_Time3;
extern lv_obj_t *ui_ICON_Current;
extern lv_obj_t *ui_ICON_Temperature;
extern lv_obj_t *ui_Panel5;
void ui_event_BTN_Pause_Scan( lv_event_t * e);
extern lv_obj_t *ui_BTN_Pause_Scan;
extern lv_obj_t *ui_ICON_Pause;
void ui_event_BTN_Stop_Scan( lv_event_t * e);
extern lv_obj_t *ui_BTN_Stop_Scan;
extern lv_obj_t *ui_ICON_Stop;
// SCREEN: ui_S2_Move
void ui_S2_Move_screen_init(void);
extern lv_obj_t *ui_S2_Move;
extern lv_obj_t *ui_UI_BG_S2;
void ui_event_BTN_Menu_Scan_S2( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Scan_S2;
extern lv_obj_t *ui_BTN_Menu_Move_S2;
void ui_event_BTN_Menu_Settings_S2( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Settings_S2;
extern lv_obj_t *ui_StatusBar_S2;
extern lv_obj_t *ui_StatusBarLbl_S2;
extern lv_obj_t *ui_ICON_PC_Online_S2;
extern lv_obj_t *ui_MovePadsPanel;
extern lv_obj_t *ui_Move_Knob_Panel;
extern lv_obj_t *ui_MOVE_Knob_BG;
void ui_event_BTN_BCK_GLOW( lv_event_t * e);
extern lv_obj_t *ui_BTN_BCK_GLOW;
void ui_event_BTN_FWD_GLOW( lv_event_t * e);
extern lv_obj_t *ui_BTN_FWD_GLOW;
void ui_event_BTN_LEFT_GLOW( lv_event_t * e);
extern lv_obj_t *ui_BTN_LEFT_GLOW;
void ui_event_BTN_RIGHT_GLOW( lv_event_t * e);
extern lv_obj_t *ui_BTN_RIGHT_GLOW;
extern lv_obj_t *ui_MOVE_Knob_TOP;
extern lv_obj_t *ui_Arrow_FWD;
extern lv_obj_t *ui_Arrow_BCK;
extern lv_obj_t *ui_Arrow_LEFT;
extern lv_obj_t *ui_Arrow_RIGHT;
extern lv_obj_t *ui_Updown_Knob_Panel;
extern lv_obj_t *ui_UPDOWN_Knob_BG;
void ui_event_BTN_UP_GLOW( lv_event_t * e);
extern lv_obj_t *ui_BTN_UP_GLOW;
void ui_event_BTN_DOWN_GLOW( lv_event_t * e);
extern lv_obj_t *ui_BTN_DOWN_GLOW;
extern lv_obj_t *ui_UPDOWN_Knob;
extern lv_obj_t *ui_Arrow_UP;
extern lv_obj_t *ui_Arrow_DOWN;
extern lv_obj_t *ui_Panel_Step_Size;
void ui_event_SLIDER_Step_Size( lv_event_t * e);
extern lv_obj_t *ui_SLIDER_Step_Size;
extern lv_obj_t *ui_LBL_Step_Size;
extern lv_obj_t *ui_PositionPanel;
extern lv_obj_t *ui_LBL_Pos_Title;
extern lv_obj_t *ui_POS_Separator1;
extern lv_obj_t *ui_POS_Separator2;
extern lv_obj_t *ui_LBL_Title_Pos_X_;
extern lv_obj_t *ui_LBL_Title_Pos_Y_;
extern lv_obj_t *ui_LBL_Title_Pos_Z_;
extern lv_obj_t *ui_LBL_X_Pos;
extern lv_obj_t *ui_LBL_Y_Pos;
extern lv_obj_t *ui_LBL_Y_Pos1;
extern lv_obj_t *ui_Status_Panel;
extern lv_obj_t *ui_POS_Separator3;
extern lv_obj_t *ui_LBL_Title_Enabled;
extern lv_obj_t *ui_LED_Enabled;
extern lv_obj_t *ui_LBL_Title_Referenced;
extern lv_obj_t *ui_LED_Referenced;
extern lv_obj_t *ui_LBL_Title_Sanity;
extern lv_obj_t *ui_LED_Sanity;
void ui_event_BTN_Reset_Pos( lv_event_t * e);
extern lv_obj_t *ui_BTN_Reset_Pos;
extern lv_obj_t *ui_BTN_LBL_Reset_pos;
void ui_event_BTN_Reference( lv_event_t * e);
extern lv_obj_t *ui_BTN_Reference;
extern lv_obj_t *ui_BTN_LBL_Reference;
void ui_event_BTN_Halt( lv_event_t * e);
extern lv_obj_t *ui_BTN_Halt;
extern lv_obj_t *ui_BTN_LBL_Halt;
void ui_event_On_BTN_Panel( lv_event_t * e);
extern lv_obj_t *ui_On_BTN_Panel;
extern lv_obj_t *ui_BTN_Icon_Turn_ON;
// SCREEN: ui_S3_Settings
void ui_S3_Settings_screen_init(void);
extern lv_obj_t *ui_S3_Settings;
extern lv_obj_t *ui_UI_BG_S3;
void ui_event_BTN_Menu_Scan_S3( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Scan_S3;
void ui_event_BTN_Menu_Move_S3( lv_event_t * e);
extern lv_obj_t *ui_BTN_Menu_Move_S3;
extern lv_obj_t *ui_BTN_Menu_Settings_S3;
extern lv_obj_t *ui_StatusBar_S3;
extern lv_obj_t *ui_StatusBarLbl_S3;
extern lv_obj_t *ui_ICON_PC_Online_S3;
extern lv_obj_t *ui_General_Settings_Panel;
extern lv_obj_t *ui_SWITCH_Post_Shutdown;
extern lv_obj_t *ui_SWITCH_Light_LEDs;
extern lv_obj_t *ui_LBL_Title_Intern_Lights;
extern lv_obj_t *ui_LBL_Title_Post_Shutdown;
extern lv_obj_t *ui_General_Status_Panel;
extern lv_obj_t *ui_LBL_Title_Estop;
extern lv_obj_t *ui_LBL_Title_Door;
extern lv_obj_t *ui_LED_EStop;
extern lv_obj_t *ui_LED_Door;
extern lv_obj_t *ui_Instr_IP_Address_Panel;
void ui_event_TXT_IP_OCT4( lv_event_t * e);
extern lv_obj_t *ui_TXT_IP_OCT4;
void ui_event_TXT_IP_OCT3( lv_event_t * e);
extern lv_obj_t *ui_TXT_IP_OCT3;
void ui_event_TXT_IP_OCT2( lv_event_t * e);
extern lv_obj_t *ui_TXT_IP_OCT2;
void ui_event_TXT_IP_OCT1( lv_event_t * e);
extern lv_obj_t *ui_TXT_IP_OCT1;
extern lv_obj_t *ui_LBL_IP_Dot;
extern lv_obj_t *ui_LBL_IP_Dot1;
extern lv_obj_t *ui_LBL_IP_Dot2;
void ui_event_KEY_IP_Input( lv_event_t * e);
extern lv_obj_t *ui_KEY_IP_Input;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ui_bg_png);   // assets\UI_bg.png
LV_IMG_DECLARE( ui_img_button_scan_png);   // assets\button_scan.png
LV_IMG_DECLARE( ui_img_button_move_png);   // assets\button_move.png
LV_IMG_DECLARE( ui_img_button_settings_png);   // assets\button_settings.png
LV_IMG_DECLARE( ui_img_icn_pc_png);   // assets\icn_pc.png
LV_IMG_DECLARE( ui_img_progress_bar_png);   // assets\progress_bar.png
LV_IMG_DECLARE( ui_img_progress_bar_top_png);   // assets\progress_bar_top.png
LV_IMG_DECLARE( ui_img_progress_bar_top_frame_png);   // assets\progress_bar_top_frame.png
LV_IMG_DECLARE( ui_img_icn_time_1_png);   // assets\icn_time_1.png
LV_IMG_DECLARE( ui_img_icn_time_2_png);   // assets\icn_time_2.png
LV_IMG_DECLARE( ui_img_current_meas_icon_png);   // assets\current_meas_icon.png
LV_IMG_DECLARE( ui_img_temp_meas_icon_png);   // assets\temp_meas_icon.png
LV_IMG_DECLARE( ui_img_icn_pause_png);   // assets\icn_pause.png
LV_IMG_DECLARE( ui_img_icn_stop_png);   // assets\icn_stop.png
LV_IMG_DECLARE( ui_img_move_buttons_bg_png);   // assets\move_buttons_bg.png
LV_IMG_DECLARE( ui_img_move_buttons_png);   // assets\move_buttons.png
LV_IMG_DECLARE( ui_img_arrow_down_png);   // assets\arrow_down.png
LV_IMG_DECLARE( ui_img_arrow_up_png);   // assets\arrow_up.png
LV_IMG_DECLARE( ui_img_arrow_left_png);   // assets\arrow_left.png
LV_IMG_DECLARE( ui_img_arrow_right_png);   // assets\arrow_right.png
LV_IMG_DECLARE( ui_img_updown_buttons_bg_png);   // assets\updown_buttons_bg.png
LV_IMG_DECLARE( ui_img_updown_buttons_png);   // assets\updown_buttons.png
LV_IMG_DECLARE( ui_img_on_icon_png);   // assets\on_icon.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
