// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>


void moveFwdBtnPressed(lv_event_t * e)
{
  uint8_t stepSize = lv_slider_get_value(ui_SLIDER_Step_Size);
  char string[64];
  sprintf(string, "Moving %u forward...", stepSize);
  lv_label_set_text(ui_StatusBarLbl_S2, string);
}

void moveFwdBtnReleased(lv_event_t * e)
{
  lv_label_set_text(ui_StatusBarLbl_S2, "Use buttons to move the probe");
}

void moveUpBtnPressed(lv_event_t * e)
{
  uint8_t stepSize = lv_slider_get_value(ui_SLIDER_Step_Size);
  char string[64];
  sprintf(string, "Moving %u up...", stepSize);
  lv_label_set_text(ui_StatusBarLbl_S2, string);
}

void moveUpBtnReleased(lv_event_t * e)
{
  lv_label_set_text(ui_StatusBarLbl_S2, "Use buttons to move the probe");
}

void moveDownBtnPressed(lv_event_t * e)
{
  uint8_t stepSize = lv_slider_get_value(ui_SLIDER_Step_Size);
  char string[64];
  sprintf(string, "Moving %u down...", stepSize);
  lv_label_set_text(ui_StatusBarLbl_S2, string);
}

void moveDownBtnReleased(lv_event_t * e)
{
  lv_label_set_text(ui_StatusBarLbl_S2, "Use buttons to move the probe");
}

void moveBackBtnPressed(lv_event_t * e)
{
  uint8_t stepSize = lv_slider_get_value(ui_SLIDER_Step_Size);
  char string[64];
  sprintf(string, "Moving %u back...", stepSize);
  lv_label_set_text(ui_StatusBarLbl_S2, string);
}

void moveBackBtnReleased(lv_event_t * e)
{
  lv_label_set_text(ui_StatusBarLbl_S2, "Use buttons to move the probe");
}

void moveLeftBtnPressed(lv_event_t * e)
{
  uint8_t stepSize = lv_slider_get_value(ui_SLIDER_Step_Size);
  char string[64];
  sprintf(string, "Moving %u left...", stepSize);
  lv_label_set_text(ui_StatusBarLbl_S2, string);
}

void moveLeftBtnReleased(lv_event_t * e)
{
  lv_label_set_text(ui_StatusBarLbl_S2, "Use buttons to move the probe");
}

void moveRightBtnPressed(lv_event_t * e)
{
  uint8_t stepSize = lv_slider_get_value(ui_SLIDER_Step_Size);
  char string[64];
  sprintf(string, "Moving %u right...", stepSize);
  lv_label_set_text(ui_StatusBarLbl_S2, string);
}

void moveRightBtnReleased(lv_event_t * e)
{
  lv_label_set_text(ui_StatusBarLbl_S2, "Use buttons to move the probe");
}
