// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void moveBackBtnPressed(lv_event_t * e);
void moveBackBtnReleased(lv_event_t * e);
void moveFwdBtnPressed(lv_event_t * e);
void moveFwdBtnReleased(lv_event_t * e);
void moveLeftBtnPressed(lv_event_t * e);
void moveLeftBtnReleased(lv_event_t * e);
void moveRightBtnPressed(lv_event_t * e);
void moveRightBtnReleased(lv_event_t * e);
void moveUpBtnPressed(lv_event_t * e);
void moveUpBtnReleased(lv_event_t * e);
void moveDownBtnPressed(lv_event_t * e);
void moveDownBtnReleased(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
