// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_S3_Settings_screen_init(void)
{
ui_S3_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_S3_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_UI_BG_S3 = lv_img_create(ui_S3_Settings);
lv_img_set_src(ui_UI_BG_S3, &ui_img_ui_bg_png);
lv_obj_set_width( ui_UI_BG_S3, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_UI_BG_S3, LV_SIZE_CONTENT);   /// 272
lv_obj_set_align( ui_UI_BG_S3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UI_BG_S3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_UI_BG_S3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Menu_Scan_S3 = lv_img_create(ui_S3_Settings);
lv_img_set_src(ui_BTN_Menu_Scan_S3, &ui_img_button_scan_png);
lv_obj_set_width( ui_BTN_Menu_Scan_S3, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Scan_S3, LV_SIZE_CONTENT);   /// 50
lv_obj_add_flag( ui_BTN_Menu_Scan_S3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Scan_S3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Scan_S3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Move_S3 = lv_img_create(ui_S3_Settings);
lv_img_set_src(ui_BTN_Menu_Move_S3, &ui_img_button_move_png);
lv_obj_set_width( ui_BTN_Menu_Move_S3, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Move_S3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Menu_Move_S3, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_BTN_Menu_Move_S3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Move_S3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Move_S3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Settings_S3 = lv_img_create(ui_S3_Settings);
lv_img_set_src(ui_BTN_Menu_Settings_S3, &ui_img_button_settings_png);
lv_obj_set_width( ui_BTN_Menu_Settings_S3, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Settings_S3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Menu_Settings_S3, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BTN_Menu_Settings_S3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Settings_S3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_StatusBar_S3 = lv_obj_create(ui_S3_Settings);
lv_obj_set_width( ui_StatusBar_S3, 400);
lv_obj_set_height( ui_StatusBar_S3, 20);
lv_obj_set_align( ui_StatusBar_S3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_StatusBar_S3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_StatusBar_S3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusBar_S3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_StatusBar_S3, lv_color_hex(0x388EE1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_StatusBar_S3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusBarLbl_S3 = lv_label_create(ui_StatusBar_S3);
lv_obj_set_width( ui_StatusBarLbl_S3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusBarLbl_S3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StatusBarLbl_S3, 0 );
lv_obj_set_y( ui_StatusBarLbl_S3, -15 );
lv_label_set_text(ui_StatusBarLbl_S3,"Adjust instrument and robot settings");
lv_obj_set_style_text_font(ui_StatusBarLbl_S3, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ICON_PC_Online_S3 = lv_img_create(ui_StatusBar_S3);
lv_img_set_src(ui_ICON_PC_Online_S3, &ui_img_icn_pc_png);
lv_obj_set_width( ui_ICON_PC_Online_S3, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_ICON_PC_Online_S3, LV_SIZE_CONTENT);   /// 22
lv_obj_set_x( ui_ICON_PC_Online_S3, 15 );
lv_obj_set_y( ui_ICON_PC_Online_S3, 0 );
lv_obj_set_align( ui_ICON_PC_Online_S3, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ICON_PC_Online_S3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_PC_Online_S3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_PC_Online_S3,128);

ui_General_Settings_Panel = lv_obj_create(ui_S3_Settings);
lv_obj_set_width( ui_General_Settings_Panel, 275);
lv_obj_set_height( ui_General_Settings_Panel, 100);
lv_obj_set_x( ui_General_Settings_Panel, 10 );
lv_obj_set_y( ui_General_Settings_Panel, 60 );
lv_obj_clear_flag( ui_General_Settings_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_General_Settings_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_General_Settings_Panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_General_Settings_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_General_Settings_Panel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SWITCH_Post_Shutdown = lv_switch_create(ui_General_Settings_Panel);
lv_obj_set_width( ui_SWITCH_Post_Shutdown, 50);
lv_obj_set_height( ui_SWITCH_Post_Shutdown, 25);
lv_obj_set_x( ui_SWITCH_Post_Shutdown, 0 );
lv_obj_set_y( ui_SWITCH_Post_Shutdown, 40 );
lv_obj_set_align( ui_SWITCH_Post_Shutdown, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_bg_color(ui_SWITCH_Post_Shutdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWITCH_Post_Shutdown, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SWITCH_Post_Shutdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SWITCH_Post_Shutdown, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SWITCH_Post_Shutdown, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SWITCH_Post_Shutdown, lv_color_hex(0x00D2FF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SWITCH_Post_Shutdown, 120, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_SWITCH_Light_LEDs = lv_switch_create(ui_General_Settings_Panel);
lv_obj_set_width( ui_SWITCH_Light_LEDs, 50);
lv_obj_set_height( ui_SWITCH_Light_LEDs, 25);
lv_obj_set_align( ui_SWITCH_Light_LEDs, LV_ALIGN_TOP_RIGHT );
lv_obj_set_style_bg_color(ui_SWITCH_Light_LEDs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SWITCH_Light_LEDs, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SWITCH_Light_LEDs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SWITCH_Light_LEDs, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SWITCH_Light_LEDs, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SWITCH_Light_LEDs, lv_color_hex(0x00D2FF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SWITCH_Light_LEDs, 120, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_LBL_Title_Intern_Lights = lv_label_create(ui_General_Settings_Panel);
lv_obj_set_width( ui_LBL_Title_Intern_Lights, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Intern_Lights, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Intern_Lights, 0 );
lv_obj_set_y( ui_LBL_Title_Intern_Lights, 5 );
lv_label_set_text(ui_LBL_Title_Intern_Lights,"Internal light:");

ui_LBL_Title_Post_Shutdown = lv_label_create(ui_General_Settings_Panel);
lv_obj_set_width( ui_LBL_Title_Post_Shutdown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Post_Shutdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Post_Shutdown, 0 );
lv_obj_set_y( ui_LBL_Title_Post_Shutdown, 45 );
lv_label_set_text(ui_LBL_Title_Post_Shutdown,"Turn off after scan:");

ui_General_Status_Panel = lv_obj_create(ui_S3_Settings);
lv_obj_set_width( ui_General_Status_Panel, 175);
lv_obj_set_height( ui_General_Status_Panel, 100);
lv_obj_set_x( ui_General_Status_Panel, 295 );
lv_obj_set_y( ui_General_Status_Panel, 60 );
lv_obj_clear_flag( ui_General_Status_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_General_Status_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_General_Status_Panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_General_Status_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_General_Status_Panel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Estop = lv_label_create(ui_General_Status_Panel);
lv_obj_set_width( ui_LBL_Title_Estop, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Estop, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Estop, 0 );
lv_obj_set_y( ui_LBL_Title_Estop, 5 );
lv_label_set_text(ui_LBL_Title_Estop,"E-Stop:");

ui_LBL_Title_Door = lv_label_create(ui_General_Status_Panel);
lv_obj_set_width( ui_LBL_Title_Door, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Door, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Door, 0 );
lv_obj_set_y( ui_LBL_Title_Door, 45 );
lv_label_set_text(ui_LBL_Title_Door,"Door:");

ui_LED_EStop = lv_obj_create(ui_General_Status_Panel);
lv_obj_set_width( ui_LED_EStop, 20);
lv_obj_set_height( ui_LED_EStop, 20);
lv_obj_set_x( ui_LED_EStop, 0 );
lv_obj_set_y( ui_LED_EStop, 2 );
lv_obj_set_align( ui_LED_EStop, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_LED_EStop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LED_EStop, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_EStop, lv_color_hex(0x3BD620), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LED_EStop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_LED_EStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_LED_EStop, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_LED_EStop, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_LED_EStop, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_LED_EStop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_LED_EStop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_EStop, lv_color_hex(0xB91717), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LED_EStop, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LED_Door = lv_obj_create(ui_General_Status_Panel);
lv_obj_set_width( ui_LED_Door, 20);
lv_obj_set_height( ui_LED_Door, 20);
lv_obj_set_x( ui_LED_Door, 0 );
lv_obj_set_y( ui_LED_Door, 42 );
lv_obj_set_align( ui_LED_Door, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_LED_Door, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LED_Door, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Door, lv_color_hex(0x204127), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LED_Door, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_LED_Door, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_LED_Door, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_LED_Door, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_LED_Door, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_LED_Door, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_LED_Door, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Door, lv_color_hex(0x3BD620), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LED_Door, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Instr_IP_Address_Panel = lv_obj_create(ui_S3_Settings);
lv_obj_set_width( ui_Instr_IP_Address_Panel, 235);
lv_obj_set_height( ui_Instr_IP_Address_Panel, 70);
lv_obj_set_x( ui_Instr_IP_Address_Panel, 10 );
lv_obj_set_y( ui_Instr_IP_Address_Panel, 170 );
lv_obj_clear_flag( ui_Instr_IP_Address_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Instr_IP_Address_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Instr_IP_Address_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Instr_IP_Address_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Instr_IP_Address_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TXT_IP_OCT4 = lv_textarea_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_TXT_IP_OCT4, 47);
lv_obj_set_height( ui_TXT_IP_OCT4, LV_SIZE_CONTENT);   /// 70
if ("1234567890"=="") lv_textarea_set_accepted_chars(ui_TXT_IP_OCT4, NULL);
else lv_textarea_set_accepted_chars(ui_TXT_IP_OCT4, "1234567890");
lv_textarea_set_max_length(ui_TXT_IP_OCT4,3);
lv_textarea_set_text(ui_TXT_IP_OCT4,"192");
lv_textarea_set_placeholder_text(ui_TXT_IP_OCT4,"192");
lv_textarea_set_one_line(ui_TXT_IP_OCT4,true);
lv_obj_set_style_border_color(ui_TXT_IP_OCT4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TXT_IP_OCT4, 20, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TXT_IP_OCT3 = lv_textarea_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_TXT_IP_OCT3, 47);
lv_obj_set_height( ui_TXT_IP_OCT3, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_TXT_IP_OCT3, 50 );
lv_obj_set_y( ui_TXT_IP_OCT3, 0 );
if ("1234567890"=="") lv_textarea_set_accepted_chars(ui_TXT_IP_OCT3, NULL);
else lv_textarea_set_accepted_chars(ui_TXT_IP_OCT3, "1234567890");
lv_textarea_set_max_length(ui_TXT_IP_OCT3,3);
lv_textarea_set_text(ui_TXT_IP_OCT3,"168");
lv_textarea_set_placeholder_text(ui_TXT_IP_OCT3,"168");
lv_textarea_set_one_line(ui_TXT_IP_OCT3,true);
lv_obj_set_style_border_color(ui_TXT_IP_OCT3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TXT_IP_OCT3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TXT_IP_OCT2 = lv_textarea_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_TXT_IP_OCT2, 47);
lv_obj_set_height( ui_TXT_IP_OCT2, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_TXT_IP_OCT2, 100 );
lv_obj_set_y( ui_TXT_IP_OCT2, 0 );
if ("1234567890"=="") lv_textarea_set_accepted_chars(ui_TXT_IP_OCT2, NULL);
else lv_textarea_set_accepted_chars(ui_TXT_IP_OCT2, "1234567890");
lv_textarea_set_text(ui_TXT_IP_OCT2,"1");
lv_textarea_set_placeholder_text(ui_TXT_IP_OCT2,"1");
lv_textarea_set_one_line(ui_TXT_IP_OCT2,true);
lv_obj_set_style_text_align(ui_TXT_IP_OCT2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TXT_IP_OCT2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TXT_IP_OCT2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TXT_IP_OCT1 = lv_textarea_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_TXT_IP_OCT1, 47);
lv_obj_set_height( ui_TXT_IP_OCT1, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_TXT_IP_OCT1, 150 );
lv_obj_set_y( ui_TXT_IP_OCT1, 0 );
if ("1234567890"=="") lv_textarea_set_accepted_chars(ui_TXT_IP_OCT1, NULL);
else lv_textarea_set_accepted_chars(ui_TXT_IP_OCT1, "1234567890");
lv_textarea_set_max_length(ui_TXT_IP_OCT1,3);
lv_textarea_set_text(ui_TXT_IP_OCT1,"137");
lv_textarea_set_placeholder_text(ui_TXT_IP_OCT1,"137");
lv_textarea_set_one_line(ui_TXT_IP_OCT1,true);
lv_obj_set_style_border_color(ui_TXT_IP_OCT1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TXT_IP_OCT1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_LBL_IP_Dot = lv_label_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_LBL_IP_Dot, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_IP_Dot, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_IP_Dot, 46 );
lv_obj_set_y( ui_LBL_IP_Dot, 10 );
lv_obj_set_align( ui_LBL_IP_Dot, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LBL_IP_Dot,".");

ui_LBL_IP_Dot1 = lv_label_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_LBL_IP_Dot1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_IP_Dot1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_IP_Dot1, 96 );
lv_obj_set_y( ui_LBL_IP_Dot1, 10 );
lv_obj_set_align( ui_LBL_IP_Dot1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LBL_IP_Dot1,".");

ui_LBL_IP_Dot2 = lv_label_create(ui_Instr_IP_Address_Panel);
lv_obj_set_width( ui_LBL_IP_Dot2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_IP_Dot2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_IP_Dot2, 146 );
lv_obj_set_y( ui_LBL_IP_Dot2, 10 );
lv_obj_set_align( ui_LBL_IP_Dot2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LBL_IP_Dot2,".");

ui_KEY_IP_Input = lv_keyboard_create(ui_S3_Settings);
lv_keyboard_set_mode(ui_KEY_IP_Input,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_KEY_IP_Input, 210);
lv_obj_set_height( ui_KEY_IP_Input, 180);
lv_obj_set_x( ui_KEY_IP_Input, -6 );
lv_obj_set_y( ui_KEY_IP_Input, 13 );
lv_obj_set_align( ui_KEY_IP_Input, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_KEY_IP_Input, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_KEY_IP_Input, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_KEY_IP_Input, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_KEY_IP_Input, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_KEY_IP_Input, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_KEY_IP_Input, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_KEY_IP_Input, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BTN_Menu_Scan_S3, ui_event_BTN_Menu_Scan_S3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Menu_Move_S3, ui_event_BTN_Menu_Move_S3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TXT_IP_OCT4, ui_event_TXT_IP_OCT4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TXT_IP_OCT3, ui_event_TXT_IP_OCT3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TXT_IP_OCT2, ui_event_TXT_IP_OCT2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TXT_IP_OCT1, ui_event_TXT_IP_OCT1, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KEY_IP_Input,ui_TXT_IP_OCT4);
lv_obj_add_event_cb(ui_KEY_IP_Input, ui_event_KEY_IP_Input, LV_EVENT_ALL, NULL);

}
