// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_S1_Scan_screen_init(void)
{
ui_S1_Scan = lv_obj_create(NULL);
lv_obj_clear_flag( ui_S1_Scan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_UI_BG_S1 = lv_img_create(ui_S1_Scan);
lv_img_set_src(ui_UI_BG_S1, &ui_img_ui_bg_png);
lv_obj_set_width( ui_UI_BG_S1, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_UI_BG_S1, LV_SIZE_CONTENT);   /// 272
lv_obj_set_align( ui_UI_BG_S1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UI_BG_S1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_UI_BG_S1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Menu_Scan_S1 = lv_img_create(ui_S1_Scan);
lv_img_set_src(ui_BTN_Menu_Scan_S1, &ui_img_button_scan_png);
lv_obj_set_width( ui_BTN_Menu_Scan_S1, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Scan_S1, LV_SIZE_CONTENT);   /// 50
lv_obj_add_flag( ui_BTN_Menu_Scan_S1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Scan_S1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Menu_Move_S1 = lv_img_create(ui_S1_Scan);
lv_img_set_src(ui_BTN_Menu_Move_S1, &ui_img_button_move_png);
lv_obj_set_width( ui_BTN_Menu_Move_S1, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Move_S1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Menu_Move_S1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_BTN_Menu_Move_S1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Move_S1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Move_S1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Settings_S1 = lv_img_create(ui_S1_Scan);
lv_img_set_src(ui_BTN_Menu_Settings_S1, &ui_img_button_settings_png);
lv_obj_set_width( ui_BTN_Menu_Settings_S1, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Settings_S1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Menu_Settings_S1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BTN_Menu_Settings_S1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Settings_S1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Settings_S1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusBar_S1 = lv_obj_create(ui_S1_Scan);
lv_obj_set_width( ui_StatusBar_S1, 400);
lv_obj_set_height( ui_StatusBar_S1, 20);
lv_obj_set_align( ui_StatusBar_S1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_StatusBar_S1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_StatusBar_S1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusBar_S1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_StatusBar_S1, lv_color_hex(0x388EE1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_StatusBar_S1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ICON_PC_Online_S1 = lv_img_create(ui_StatusBar_S1);
lv_img_set_src(ui_ICON_PC_Online_S1, &ui_img_icn_pc_png);
lv_obj_set_width( ui_ICON_PC_Online_S1, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_ICON_PC_Online_S1, LV_SIZE_CONTENT);   /// 22
lv_obj_set_x( ui_ICON_PC_Online_S1, 15 );
lv_obj_set_y( ui_ICON_PC_Online_S1, 0 );
lv_obj_set_align( ui_ICON_PC_Online_S1, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ICON_PC_Online_S1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_PC_Online_S1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_PC_Online_S1,128);

ui_StatusBarLbl_S1 = lv_label_create(ui_StatusBar_S1);
lv_obj_set_width( ui_StatusBarLbl_S1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusBarLbl_S1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StatusBarLbl_S1, 0 );
lv_obj_set_y( ui_StatusBarLbl_S1, -15 );
lv_label_set_text(ui_StatusBarLbl_S1,"Currently no scans are running");
lv_obj_set_style_text_font(ui_StatusBarLbl_S1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Progress_Panel = lv_obj_create(ui_S1_Scan);
lv_obj_set_width( ui_Progress_Panel, 170);
lv_obj_set_height( ui_Progress_Panel, 180);
lv_obj_set_x( ui_Progress_Panel, 10 );
lv_obj_set_y( ui_Progress_Panel, 60 );
lv_obj_clear_flag( ui_Progress_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Progress_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Progress_Panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Progress_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Progress_Panel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PROG_BAR_Scan_Progress = lv_slider_create(ui_Progress_Panel);
lv_slider_set_value( ui_PROG_BAR_Scan_Progress, 70, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_PROG_BAR_Scan_Progress)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_PROG_BAR_Scan_Progress, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_PROG_BAR_Scan_Progress, 150);
lv_obj_set_height( ui_PROG_BAR_Scan_Progress, 153);
lv_obj_set_align( ui_PROG_BAR_Scan_Progress, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_PROG_BAR_Scan_Progress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PROG_BAR_Scan_Progress, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PROG_BAR_Scan_Progress, &ui_img_progress_bar_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_PROG_BAR_Scan_Progress, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PROG_BAR_Scan_Progress, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PROG_BAR_Scan_Progress, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PROG_BAR_Scan_Progress, &ui_img_progress_bar_top_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_PROG_BAR_Scan_Progress, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PROG_BAR_Scan_Progress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PROG_BAR_Scan_Progress, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TopFrame = lv_img_create(ui_PROG_BAR_Scan_Progress);
lv_img_set_src(ui_TopFrame, &ui_img_progress_bar_top_frame_png);
lv_obj_set_width( ui_TopFrame, LV_SIZE_CONTENT);  /// 150
lv_obj_set_height( ui_TopFrame, LV_SIZE_CONTENT);   /// 150
lv_obj_set_align( ui_TopFrame, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_TopFrame, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TopFrame, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LBL_Progress_Percent = lv_label_create(ui_Progress_Panel);
lv_obj_set_width( ui_LBL_Progress_Percent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Progress_Percent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Progress_Percent, 0 );
lv_obj_set_y( ui_LBL_Progress_Percent, 75 );
lv_obj_set_align( ui_LBL_Progress_Percent, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBL_Progress_Percent,"70%");

ui_Scan_Time_Panel = lv_obj_create(ui_S1_Scan);
lv_obj_set_width( ui_Scan_Time_Panel, 280);
lv_obj_set_height( ui_Scan_Time_Panel, 55);
lv_obj_set_x( ui_Scan_Time_Panel, 190 );
lv_obj_set_y( ui_Scan_Time_Panel, 60 );
lv_obj_clear_flag( ui_Scan_Time_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Scan_Time_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Scan_Time_Panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Scan_Time_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Scan_Time_Panel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Scan_Time = lv_label_create(ui_Scan_Time_Panel);
lv_obj_set_width( ui_LBL_Title_Scan_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Scan_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Scan_Time, 25 );
lv_obj_set_y( ui_LBL_Title_Scan_Time, -10 );
lv_label_set_text(ui_LBL_Title_Scan_Time,"Scan Time");
lv_obj_set_style_text_font(ui_LBL_Title_Scan_Time, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Remaining_Time = lv_label_create(ui_Scan_Time_Panel);
lv_obj_set_width( ui_LBL_Title_Remaining_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Remaining_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Remaining_Time, 150 );
lv_obj_set_y( ui_LBL_Title_Remaining_Time, -10 );
lv_label_set_text(ui_LBL_Title_Remaining_Time,"Remaining time");
lv_obj_set_style_text_font(ui_LBL_Title_Remaining_Time, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Separator = lv_obj_create(ui_Scan_Time_Panel);
lv_obj_set_width( ui_Separator, 4);
lv_obj_set_height( ui_Separator, 40);
lv_obj_set_x( ui_Separator, 120 );
lv_obj_set_y( ui_Separator, -10 );
lv_obj_clear_flag( ui_Separator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Separator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Separator, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Separator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Separator, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Scan_Time = lv_label_create(ui_Scan_Time_Panel);
lv_obj_set_width( ui_LBL_Scan_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Scan_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Scan_Time, 45 );
lv_obj_set_y( ui_LBL_Scan_Time, 10 );
lv_label_set_text(ui_LBL_Scan_Time,"01:25");

ui_LBL_Scan_Time1 = lv_label_create(ui_Scan_Time_Panel);
lv_obj_set_width( ui_LBL_Scan_Time1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Scan_Time1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Scan_Time1, 185 );
lv_obj_set_y( ui_LBL_Scan_Time1, 10 );
lv_label_set_text(ui_LBL_Scan_Time1,"02:17");

ui_ICON_Scan_Time_Clock = lv_img_create(ui_Scan_Time_Panel);
lv_img_set_src(ui_ICON_Scan_Time_Clock, &ui_img_icn_time_1_png);
lv_obj_set_width( ui_ICON_Scan_Time_Clock, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_ICON_Scan_Time_Clock, LV_SIZE_CONTENT);   /// 23
lv_obj_set_x( ui_ICON_Scan_Time_Clock, 20 );
lv_obj_set_y( ui_ICON_Scan_Time_Clock, 6 );
lv_obj_add_flag( ui_ICON_Scan_Time_Clock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_Scan_Time_Clock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_Scan_Time_Clock,200);

ui_ICON_Remaining_Time_Clock = lv_img_create(ui_Scan_Time_Panel);
lv_img_set_src(ui_ICON_Remaining_Time_Clock, &ui_img_icn_time_2_png);
lv_obj_set_width( ui_ICON_Remaining_Time_Clock, LV_SIZE_CONTENT);  /// 23
lv_obj_set_height( ui_ICON_Remaining_Time_Clock, LV_SIZE_CONTENT);   /// 23
lv_obj_set_x( ui_ICON_Remaining_Time_Clock, 160 );
lv_obj_set_y( ui_ICON_Remaining_Time_Clock, 6 );
lv_obj_add_flag( ui_ICON_Remaining_Time_Clock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_Remaining_Time_Clock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_Remaining_Time_Clock,200);

ui_Scanner_Param_Panel = lv_obj_create(ui_S1_Scan);
lv_obj_set_width( ui_Scanner_Param_Panel, 280);
lv_obj_set_height( ui_Scanner_Param_Panel, 55);
lv_obj_set_x( ui_Scanner_Param_Panel, 190 );
lv_obj_set_y( ui_Scanner_Param_Panel, 125 );
lv_obj_clear_flag( ui_Scanner_Param_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Scanner_Param_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Scanner_Param_Panel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Scanner_Param_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Scanner_Param_Panel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Average_Current = lv_label_create(ui_Scanner_Param_Panel);
lv_obj_set_width( ui_LBL_Title_Average_Current, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Average_Current, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Average_Current, 5 );
lv_obj_set_y( ui_LBL_Title_Average_Current, -10 );
lv_label_set_text(ui_LBL_Title_Average_Current,"Avg. Motor Current");
lv_obj_set_style_text_font(ui_LBL_Title_Average_Current, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Remaining_Time1 = lv_label_create(ui_Scanner_Param_Panel);
lv_obj_set_width( ui_LBL_Title_Remaining_Time1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Remaining_Time1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Remaining_Time1, 150 );
lv_obj_set_y( ui_LBL_Title_Remaining_Time1, -10 );
lv_label_set_text(ui_LBL_Title_Remaining_Time1,"Avg. Contr. Temp.");
lv_obj_set_style_text_font(ui_LBL_Title_Remaining_Time1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Separator1 = lv_obj_create(ui_Scanner_Param_Panel);
lv_obj_set_width( ui_Separator1, 4);
lv_obj_set_height( ui_Separator1, 40);
lv_obj_set_x( ui_Separator1, 120 );
lv_obj_set_y( ui_Separator1, -10 );
lv_obj_clear_flag( ui_Separator1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Separator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Separator1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Separator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Separator1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Scan_Time2 = lv_label_create(ui_Scanner_Param_Panel);
lv_obj_set_width( ui_LBL_Scan_Time2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Scan_Time2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Scan_Time2, 45 );
lv_obj_set_y( ui_LBL_Scan_Time2, 10 );
lv_label_set_text(ui_LBL_Scan_Time2,"3.32A");

ui_LBL_Scan_Time3 = lv_label_create(ui_Scanner_Param_Panel);
lv_obj_set_width( ui_LBL_Scan_Time3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Scan_Time3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Scan_Time3, 180 );
lv_obj_set_y( ui_LBL_Scan_Time3, 10 );
lv_label_set_text(ui_LBL_Scan_Time3,"30.1°C");

ui_ICON_Current = lv_img_create(ui_Scanner_Param_Panel);
lv_img_set_src(ui_ICON_Current, &ui_img_current_meas_icon_png);
lv_obj_set_width( ui_ICON_Current, LV_SIZE_CONTENT);  /// 23
lv_obj_set_height( ui_ICON_Current, LV_SIZE_CONTENT);   /// 38
lv_obj_set_x( ui_ICON_Current, 20 );
lv_obj_set_y( ui_ICON_Current, 0 );
lv_obj_add_flag( ui_ICON_Current, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_Current, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_Current,120);

ui_ICON_Temperature = lv_img_create(ui_Scanner_Param_Panel);
lv_img_set_src(ui_ICON_Temperature, &ui_img_temp_meas_icon_png);
lv_obj_set_width( ui_ICON_Temperature, LV_SIZE_CONTENT);  /// 11
lv_obj_set_height( ui_ICON_Temperature, LV_SIZE_CONTENT);   /// 23
lv_obj_set_x( ui_ICON_Temperature, 160 );
lv_obj_set_y( ui_ICON_Temperature, 6 );
lv_obj_add_flag( ui_ICON_Temperature, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_Temperature, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel5 = lv_obj_create(ui_S1_Scan);
lv_obj_set_width( ui_Panel5, 275);
lv_obj_set_height( ui_Panel5, 69);
lv_obj_set_x( ui_Panel5, 190 );
lv_obj_set_y( ui_Panel5, 183 );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Pause_Scan = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_BTN_Pause_Scan, 62);
lv_obj_set_height( ui_BTN_Pause_Scan, 50);
lv_obj_set_x( ui_BTN_Pause_Scan, 20 );
lv_obj_set_y( ui_BTN_Pause_Scan, -11 );
lv_obj_add_flag( ui_BTN_Pause_Scan, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_Pause_Scan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_Pause_Scan, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_Pause_Scan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Pause_Scan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Pause_Scan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BTN_Pause_Scan, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_Pause_Scan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Pause_Scan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_Pause_Scan, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_Pause_Scan, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_Pause_Scan, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Pause_Scan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Pause_Scan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_Pause_Scan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_BTN_Pause_Scan, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_BTN_Pause_Scan, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_BTN_Pause_Scan, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_ICON_Pause = lv_img_create(ui_BTN_Pause_Scan);
lv_img_set_src(ui_ICON_Pause, &ui_img_icn_pause_png);
lv_obj_set_width( ui_ICON_Pause, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_ICON_Pause, LV_SIZE_CONTENT);   /// 40
lv_obj_set_align( ui_ICON_Pause, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ICON_Pause, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_Pause, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_Pause,100);
lv_obj_set_style_img_recolor(ui_ICON_Pause, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_ICON_Pause, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_BTN_Stop_Scan = lv_btn_create(ui_Panel5);
lv_obj_set_width( ui_BTN_Stop_Scan, 62);
lv_obj_set_height( ui_BTN_Stop_Scan, 50);
lv_obj_set_x( ui_BTN_Stop_Scan, 160 );
lv_obj_set_y( ui_BTN_Stop_Scan, -11 );
lv_obj_add_flag( ui_BTN_Stop_Scan, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_Stop_Scan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_Stop_Scan, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_Stop_Scan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Stop_Scan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Stop_Scan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BTN_Stop_Scan, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_Stop_Scan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Stop_Scan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_Stop_Scan, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_Stop_Scan, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_Stop_Scan, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Stop_Scan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Stop_Scan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Stop_Scan, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_BTN_Stop_Scan, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ICON_Stop = lv_img_create(ui_BTN_Stop_Scan);
lv_img_set_src(ui_ICON_Stop, &ui_img_icn_stop_png);
lv_obj_set_width( ui_ICON_Stop, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ICON_Stop, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ICON_Stop, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ICON_Stop, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_Stop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_Stop,100);
lv_obj_set_style_img_recolor(ui_ICON_Stop, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_ICON_Stop, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_ICON_Stop, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_ICON_Stop, 255, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_BTN_Menu_Move_S1, ui_event_BTN_Menu_Move_S1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Menu_Settings_S1, ui_event_BTN_Menu_Settings_S1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PROG_BAR_Scan_Progress, ui_event_PROG_BAR_Scan_Progress, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Pause_Scan, ui_event_BTN_Pause_Scan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Stop_Scan, ui_event_BTN_Stop_Scan, LV_EVENT_ALL, NULL);

}
