// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_S2_Move_screen_init(void)
{
ui_S2_Move = lv_obj_create(NULL);
lv_obj_clear_flag( ui_S2_Move, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_UI_BG_S2 = lv_img_create(ui_S2_Move);
lv_img_set_src(ui_UI_BG_S2, &ui_img_ui_bg_png);
lv_obj_set_width( ui_UI_BG_S2, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_UI_BG_S2, LV_SIZE_CONTENT);   /// 272
lv_obj_set_align( ui_UI_BG_S2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UI_BG_S2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_UI_BG_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Menu_Scan_S2 = lv_img_create(ui_S2_Move);
lv_img_set_src(ui_BTN_Menu_Scan_S2, &ui_img_button_scan_png);
lv_obj_set_width( ui_BTN_Menu_Scan_S2, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Scan_S2, LV_SIZE_CONTENT);   /// 50
lv_obj_add_flag( ui_BTN_Menu_Scan_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Scan_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Scan_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Menu_Move_S2 = lv_img_create(ui_S2_Move);
lv_img_set_src(ui_BTN_Menu_Move_S2, &ui_img_button_move_png);
lv_obj_set_width( ui_BTN_Menu_Move_S2, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Move_S2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Menu_Move_S2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_BTN_Menu_Move_S2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Move_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Menu_Settings_S2 = lv_img_create(ui_S2_Move);
lv_img_set_src(ui_BTN_Menu_Settings_S2, &ui_img_button_settings_png);
lv_obj_set_width( ui_BTN_Menu_Settings_S2, LV_SIZE_CONTENT);  /// 160
lv_obj_set_height( ui_BTN_Menu_Settings_S2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Menu_Settings_S2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BTN_Menu_Settings_S2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Menu_Settings_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_BTN_Menu_Settings_S2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusBar_S2 = lv_obj_create(ui_S2_Move);
lv_obj_set_width( ui_StatusBar_S2, 400);
lv_obj_set_height( ui_StatusBar_S2, 20);
lv_obj_set_align( ui_StatusBar_S2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_StatusBar_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_StatusBar_S2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusBar_S2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_StatusBar_S2, lv_color_hex(0x388EE1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_StatusBar_S2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusBarLbl_S2 = lv_label_create(ui_StatusBar_S2);
lv_obj_set_width( ui_StatusBarLbl_S2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StatusBarLbl_S2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StatusBarLbl_S2, 0 );
lv_obj_set_y( ui_StatusBarLbl_S2, -15 );
lv_label_set_text(ui_StatusBarLbl_S2,"Use buttons to move the probe");
lv_obj_set_style_text_font(ui_StatusBarLbl_S2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ICON_PC_Online_S2 = lv_img_create(ui_StatusBar_S2);
lv_img_set_src(ui_ICON_PC_Online_S2, &ui_img_icn_pc_png);
lv_obj_set_width( ui_ICON_PC_Online_S2, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_ICON_PC_Online_S2, LV_SIZE_CONTENT);   /// 22
lv_obj_set_x( ui_ICON_PC_Online_S2, 15 );
lv_obj_set_y( ui_ICON_PC_Online_S2, 0 );
lv_obj_set_align( ui_ICON_PC_Online_S2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ICON_PC_Online_S2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ICON_PC_Online_S2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ICON_PC_Online_S2,128);

ui_MovePadsPanel = lv_obj_create(ui_S2_Move);
lv_obj_set_width( ui_MovePadsPanel, 255);
lv_obj_set_height( ui_MovePadsPanel, 185);
lv_obj_set_x( ui_MovePadsPanel, 10 );
lv_obj_set_y( ui_MovePadsPanel, 60 );
lv_obj_clear_flag( ui_MovePadsPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MovePadsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MovePadsPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MovePadsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MovePadsPanel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Move_Knob_Panel = lv_obj_create(ui_MovePadsPanel);
lv_obj_set_width( ui_Move_Knob_Panel, 180);
lv_obj_set_height( ui_Move_Knob_Panel, 180);
lv_obj_set_x( ui_Move_Knob_Panel, 49 );
lv_obj_set_y( ui_Move_Knob_Panel, -24 );
lv_obj_clear_flag( ui_Move_Knob_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Move_Knob_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Move_Knob_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Move_Knob_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MOVE_Knob_BG = lv_img_create(ui_Move_Knob_Panel);
lv_img_set_src(ui_MOVE_Knob_BG, &ui_img_move_buttons_bg_png);
lv_obj_set_width( ui_MOVE_Knob_BG, LV_SIZE_CONTENT);  /// 130
lv_obj_set_height( ui_MOVE_Knob_BG, LV_SIZE_CONTENT);   /// 130
lv_obj_set_align( ui_MOVE_Knob_BG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MOVE_Knob_BG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MOVE_Knob_BG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_BCK_GLOW = lv_obj_create(ui_Move_Knob_Panel);
lv_obj_set_width( ui_BTN_BCK_GLOW, 50);
lv_obj_set_height( ui_BTN_BCK_GLOW, 50);
lv_obj_set_x( ui_BTN_BCK_GLOW, 0 );
lv_obj_set_y( ui_BTN_BCK_GLOW, -40 );
lv_obj_set_align( ui_BTN_BCK_GLOW, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_BCK_GLOW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_BCK_GLOW, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_BCK_GLOW, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_BCK_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_BCK_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_BCK_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_BCK_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_BCK_GLOW, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_BCK_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_BCK_GLOW, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_BCK_GLOW, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_BCK_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_FWD_GLOW = lv_obj_create(ui_Move_Knob_Panel);
lv_obj_set_width( ui_BTN_FWD_GLOW, 50);
lv_obj_set_height( ui_BTN_FWD_GLOW, 50);
lv_obj_set_x( ui_BTN_FWD_GLOW, 0 );
lv_obj_set_y( ui_BTN_FWD_GLOW, 40 );
lv_obj_set_align( ui_BTN_FWD_GLOW, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_FWD_GLOW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_FWD_GLOW, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_FWD_GLOW, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_FWD_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_FWD_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_FWD_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_FWD_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_FWD_GLOW, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_FWD_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_FWD_GLOW, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_FWD_GLOW, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_FWD_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_LEFT_GLOW = lv_obj_create(ui_Move_Knob_Panel);
lv_obj_set_width( ui_BTN_LEFT_GLOW, 50);
lv_obj_set_height( ui_BTN_LEFT_GLOW, 50);
lv_obj_set_x( ui_BTN_LEFT_GLOW, -40 );
lv_obj_set_y( ui_BTN_LEFT_GLOW, 0 );
lv_obj_set_align( ui_BTN_LEFT_GLOW, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_LEFT_GLOW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_LEFT_GLOW, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_LEFT_GLOW, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_LEFT_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_LEFT_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_LEFT_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_LEFT_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_LEFT_GLOW, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_LEFT_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_LEFT_GLOW, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_LEFT_GLOW, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_LEFT_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_RIGHT_GLOW = lv_obj_create(ui_Move_Knob_Panel);
lv_obj_set_width( ui_BTN_RIGHT_GLOW, 50);
lv_obj_set_height( ui_BTN_RIGHT_GLOW, 50);
lv_obj_set_x( ui_BTN_RIGHT_GLOW, 40 );
lv_obj_set_y( ui_BTN_RIGHT_GLOW, 0 );
lv_obj_set_align( ui_BTN_RIGHT_GLOW, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_RIGHT_GLOW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_RIGHT_GLOW, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_RIGHT_GLOW, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_RIGHT_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_RIGHT_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_RIGHT_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_RIGHT_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_RIGHT_GLOW, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_RIGHT_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_RIGHT_GLOW, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_RIGHT_GLOW, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_RIGHT_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MOVE_Knob_TOP = lv_img_create(ui_Move_Knob_Panel);
lv_img_set_src(ui_MOVE_Knob_TOP, &ui_img_move_buttons_png);
lv_obj_set_width( ui_MOVE_Knob_TOP, LV_SIZE_CONTENT);  /// 130
lv_obj_set_height( ui_MOVE_Knob_TOP, LV_SIZE_CONTENT);   /// 130
lv_obj_set_align( ui_MOVE_Knob_TOP, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MOVE_Knob_TOP, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MOVE_Knob_TOP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arrow_FWD = lv_img_create(ui_Move_Knob_Panel);
lv_img_set_src(ui_Arrow_FWD, &ui_img_arrow_down_png);
lv_obj_set_width( ui_Arrow_FWD, LV_SIZE_CONTENT);  /// 3
lv_obj_set_height( ui_Arrow_FWD, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_Arrow_FWD, 0 );
lv_obj_set_y( ui_Arrow_FWD, 47 );
lv_obj_set_align( ui_Arrow_FWD, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_FWD, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_FWD, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Arrow_FWD,128);
lv_obj_set_style_img_recolor(ui_Arrow_FWD, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_FWD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_FWD, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_FWD, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_BCK = lv_img_create(ui_Move_Knob_Panel);
lv_img_set_src(ui_Arrow_BCK, &ui_img_arrow_up_png);
lv_obj_set_width( ui_Arrow_BCK, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Arrow_BCK, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Arrow_BCK, 0 );
lv_obj_set_y( ui_Arrow_BCK, -47 );
lv_obj_set_align( ui_Arrow_BCK, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_BCK, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_BCK, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Arrow_BCK,128);
lv_obj_set_style_img_recolor(ui_Arrow_BCK, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_BCK, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_BCK, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_BCK, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_LEFT = lv_img_create(ui_Move_Knob_Panel);
lv_img_set_src(ui_Arrow_LEFT, &ui_img_arrow_left_png);
lv_obj_set_width( ui_Arrow_LEFT, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Arrow_LEFT, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Arrow_LEFT, -47 );
lv_obj_set_y( ui_Arrow_LEFT, 0 );
lv_obj_set_align( ui_Arrow_LEFT, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_LEFT, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_LEFT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Arrow_LEFT,128);
lv_obj_set_style_img_recolor(ui_Arrow_LEFT, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_LEFT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_LEFT, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_LEFT, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_RIGHT = lv_img_create(ui_Move_Knob_Panel);
lv_img_set_src(ui_Arrow_RIGHT, &ui_img_arrow_right_png);
lv_obj_set_width( ui_Arrow_RIGHT, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Arrow_RIGHT, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Arrow_RIGHT, 47 );
lv_obj_set_y( ui_Arrow_RIGHT, 0 );
lv_obj_set_align( ui_Arrow_RIGHT, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_RIGHT, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_RIGHT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Arrow_RIGHT,128);
lv_obj_set_style_img_recolor(ui_Arrow_RIGHT, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_RIGHT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_RIGHT, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_RIGHT, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Updown_Knob_Panel = lv_obj_create(ui_MovePadsPanel);
lv_obj_set_width( ui_Updown_Knob_Panel, 70);
lv_obj_set_height( ui_Updown_Knob_Panel, 180);
lv_obj_set_x( ui_Updown_Knob_Panel, -13 );
lv_obj_set_y( ui_Updown_Knob_Panel, -26 );
lv_obj_clear_flag( ui_Updown_Knob_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Updown_Knob_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Updown_Knob_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Updown_Knob_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UPDOWN_Knob_BG = lv_img_create(ui_Updown_Knob_Panel);
lv_img_set_src(ui_UPDOWN_Knob_BG, &ui_img_updown_buttons_bg_png);
lv_obj_set_width( ui_UPDOWN_Knob_BG, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_UPDOWN_Knob_BG, LV_SIZE_CONTENT);   /// 150
lv_obj_set_align( ui_UPDOWN_Knob_BG, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_UPDOWN_Knob_BG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_UPDOWN_Knob_BG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_UP_GLOW = lv_obj_create(ui_Updown_Knob_Panel);
lv_obj_set_width( ui_BTN_UP_GLOW, 30);
lv_obj_set_height( ui_BTN_UP_GLOW, 30);
lv_obj_set_x( ui_BTN_UP_GLOW, 1 );
lv_obj_set_y( ui_BTN_UP_GLOW, -47 );
lv_obj_set_align( ui_BTN_UP_GLOW, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_UP_GLOW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_UP_GLOW, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_UP_GLOW, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_UP_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_UP_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_UP_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_UP_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_UP_GLOW, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_UP_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_UP_GLOW, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_UP_GLOW, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_UP_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_DOWN_GLOW = lv_obj_create(ui_Updown_Knob_Panel);
lv_obj_set_width( ui_BTN_DOWN_GLOW, 30);
lv_obj_set_height( ui_BTN_DOWN_GLOW, 30);
lv_obj_set_x( ui_BTN_DOWN_GLOW, 1 );
lv_obj_set_y( ui_BTN_DOWN_GLOW, 50 );
lv_obj_set_align( ui_BTN_DOWN_GLOW, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_BTN_DOWN_GLOW, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_DOWN_GLOW, 60, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_DOWN_GLOW, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_DOWN_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_DOWN_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_DOWN_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_DOWN_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_DOWN_GLOW, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_DOWN_GLOW, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_DOWN_GLOW, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_DOWN_GLOW, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_BTN_DOWN_GLOW, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UPDOWN_Knob = lv_img_create(ui_Updown_Knob_Panel);
lv_img_set_src(ui_UPDOWN_Knob, &ui_img_updown_buttons_png);
lv_obj_set_width( ui_UPDOWN_Knob, LV_SIZE_CONTENT);  /// 26
lv_obj_set_height( ui_UPDOWN_Knob, LV_SIZE_CONTENT);   /// 130
lv_obj_set_x( ui_UPDOWN_Knob, 1 );
lv_obj_set_y( ui_UPDOWN_Knob, 1 );
lv_obj_set_align( ui_UPDOWN_Knob, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UPDOWN_Knob, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_UPDOWN_Knob, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arrow_UP = lv_img_create(ui_Updown_Knob_Panel);
lv_img_set_src(ui_Arrow_UP, &ui_img_arrow_up_png);
lv_obj_set_width( ui_Arrow_UP, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Arrow_UP, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Arrow_UP, 1 );
lv_obj_set_y( ui_Arrow_UP, -56 );
lv_obj_set_align( ui_Arrow_UP, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_UP, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_UP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Arrow_UP,128);
lv_obj_set_style_img_recolor(ui_Arrow_UP, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_UP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_UP, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_UP, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Arrow_DOWN = lv_img_create(ui_Updown_Knob_Panel);
lv_img_set_src(ui_Arrow_DOWN, &ui_img_arrow_down_png);
lv_obj_set_width( ui_Arrow_DOWN, LV_SIZE_CONTENT);  /// 3
lv_obj_set_height( ui_Arrow_DOWN, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_Arrow_DOWN, 0 );
lv_obj_set_y( ui_Arrow_DOWN, 57 );
lv_obj_set_align( ui_Arrow_DOWN, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_DOWN, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_DOWN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Arrow_DOWN,128);
lv_obj_set_style_img_recolor(ui_Arrow_DOWN, lv_color_hex(0xABC1ED), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Arrow_DOWN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_Arrow_DOWN, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_Arrow_DOWN, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Panel_Step_Size = lv_obj_create(ui_MovePadsPanel);
lv_obj_set_width( ui_Panel_Step_Size, 245);
lv_obj_set_height( ui_Panel_Step_Size, 35);
lv_obj_set_x( ui_Panel_Step_Size, -15 );
lv_obj_set_y( ui_Panel_Step_Size, 17 );
lv_obj_set_align( ui_Panel_Step_Size, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_Panel_Step_Size, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_Step_Size, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Step_Size, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Step_Size, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SLIDER_Step_Size = lv_slider_create(ui_Panel_Step_Size);
lv_slider_set_range(ui_SLIDER_Step_Size, 1,50);
lv_slider_set_value( ui_SLIDER_Step_Size, 1, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SLIDER_Step_Size)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SLIDER_Step_Size, 1, LV_ANIM_OFF);
lv_obj_set_width( ui_SLIDER_Step_Size, 127);
lv_obj_set_height( ui_SLIDER_Step_Size, 10);
lv_obj_set_x( ui_SLIDER_Step_Size, 10 );
lv_obj_set_y( ui_SLIDER_Step_Size, -1 );

lv_obj_set_style_bg_color(ui_SLIDER_Step_Size, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SLIDER_Step_Size, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_LBL_Step_Size = lv_label_create(ui_Panel_Step_Size);
lv_obj_set_width( ui_LBL_Step_Size, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Step_Size, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Step_Size, 72 );
lv_obj_set_y( ui_LBL_Step_Size, 2 );
lv_obj_set_align( ui_LBL_Step_Size, LV_ALIGN_CENTER );
lv_label_set_text(ui_LBL_Step_Size,"Step = 1 mm");
lv_obj_set_style_text_font(ui_LBL_Step_Size, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PositionPanel = lv_obj_create(ui_S2_Move);
lv_obj_set_width( ui_PositionPanel, 195);
lv_obj_set_height( ui_PositionPanel, 65);
lv_obj_set_x( ui_PositionPanel, 275 );
lv_obj_set_y( ui_PositionPanel, 60 );
lv_obj_clear_flag( ui_PositionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PositionPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PositionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PositionPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PositionPanel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Pos_Title = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_Pos_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Pos_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Pos_Title, 0 );
lv_obj_set_y( ui_LBL_Pos_Title, -10 );
lv_obj_set_align( ui_LBL_Pos_Title, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LBL_Pos_Title,"Position [mm]");
lv_obj_set_style_text_font(ui_LBL_Pos_Title, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_POS_Separator1 = lv_obj_create(ui_PositionPanel);
lv_obj_set_width( ui_POS_Separator1, 4);
lv_obj_set_height( ui_POS_Separator1, 35);
lv_obj_set_x( ui_POS_Separator1, 45 );
lv_obj_set_y( ui_POS_Separator1, 5 );
lv_obj_clear_flag( ui_POS_Separator1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_POS_Separator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_POS_Separator1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_POS_Separator1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_POS_Separator1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_POS_Separator2 = lv_obj_create(ui_PositionPanel);
lv_obj_set_width( ui_POS_Separator2, 4);
lv_obj_set_height( ui_POS_Separator2, 35);
lv_obj_set_x( ui_POS_Separator2, 110 );
lv_obj_set_y( ui_POS_Separator2, 5 );
lv_obj_clear_flag( ui_POS_Separator2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_POS_Separator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_POS_Separator2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_POS_Separator2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_POS_Separator2, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Pos_X_ = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_Title_Pos_X_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Pos_X_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Pos_X_, 12 );
lv_obj_set_y( ui_LBL_Title_Pos_X_, 7 );
lv_label_set_text(ui_LBL_Title_Pos_X_,"X");
lv_obj_set_style_text_font(ui_LBL_Title_Pos_X_, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Pos_Y_ = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_Title_Pos_Y_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Pos_Y_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Pos_Y_, 77 );
lv_obj_set_y( ui_LBL_Title_Pos_Y_, 7 );
lv_label_set_text(ui_LBL_Title_Pos_Y_,"Y");
lv_obj_set_style_text_font(ui_LBL_Title_Pos_Y_, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Pos_Z_ = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_Title_Pos_Z_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Pos_Z_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Pos_Z_, 142 );
lv_obj_set_y( ui_LBL_Title_Pos_Z_, 7 );
lv_label_set_text(ui_LBL_Title_Pos_Z_,"Z");
lv_obj_set_style_text_font(ui_LBL_Title_Pos_Z_, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_X_Pos = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_X_Pos, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_X_Pos, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_X_Pos, -3 );
lv_obj_set_y( ui_LBL_X_Pos, 20 );
lv_label_set_text(ui_LBL_X_Pos,"215.52");
lv_obj_set_style_text_font(ui_LBL_X_Pos, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Y_Pos = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_Y_Pos, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Y_Pos, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Y_Pos, 62 );
lv_obj_set_y( ui_LBL_Y_Pos, 20 );
lv_label_set_text(ui_LBL_Y_Pos,"102.12");
lv_obj_set_style_text_font(ui_LBL_Y_Pos, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Y_Pos1 = lv_label_create(ui_PositionPanel);
lv_obj_set_width( ui_LBL_Y_Pos1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Y_Pos1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Y_Pos1, 127 );
lv_obj_set_y( ui_LBL_Y_Pos1, 20 );
lv_label_set_text(ui_LBL_Y_Pos1,"24.87");
lv_obj_set_style_text_font(ui_LBL_Y_Pos1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Panel = lv_obj_create(ui_S2_Move);
lv_obj_set_width( ui_Status_Panel, 195);
lv_obj_set_height( ui_Status_Panel, 115);
lv_obj_set_x( ui_Status_Panel, 275 );
lv_obj_set_y( ui_Status_Panel, 130 );
lv_obj_clear_flag( ui_Status_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Status_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Status_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Status_Panel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_POS_Separator3 = lv_obj_create(ui_Status_Panel);
lv_obj_set_width( ui_POS_Separator3, 4);
lv_obj_set_height( ui_POS_Separator3, 95);
lv_obj_set_x( ui_POS_Separator3, 82 );
lv_obj_set_y( ui_POS_Separator3, -6 );
lv_obj_clear_flag( ui_POS_Separator3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_POS_Separator3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_POS_Separator3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_POS_Separator3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_POS_Separator3, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LBL_Title_Enabled = lv_label_create(ui_Status_Panel);
lv_obj_set_width( ui_LBL_Title_Enabled, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Enabled, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_LBL_Title_Enabled,"Enabled:");
lv_obj_set_style_text_font(ui_LBL_Title_Enabled, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LED_Enabled = lv_obj_create(ui_Status_Panel);
lv_obj_set_width( ui_LED_Enabled, 12);
lv_obj_set_height( ui_LED_Enabled, 12);
lv_obj_set_x( ui_LED_Enabled, 60 );
lv_obj_set_y( ui_LED_Enabled, 0 );
lv_obj_clear_flag( ui_LED_Enabled, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LED_Enabled, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Enabled, lv_color_hex(0x204127), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LED_Enabled, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LED_Enabled, lv_color_hex(0x877D7D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LED_Enabled, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Enabled, lv_color_hex(0x3BD620), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LED_Enabled, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LBL_Title_Referenced = lv_label_create(ui_Status_Panel);
lv_obj_set_width( ui_LBL_Title_Referenced, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Referenced, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Referenced, 0 );
lv_obj_set_y( ui_LBL_Title_Referenced, 33 );
lv_label_set_text(ui_LBL_Title_Referenced,"Refer.:");
lv_obj_set_style_text_font(ui_LBL_Title_Referenced, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LED_Referenced = lv_obj_create(ui_Status_Panel);
lv_obj_set_width( ui_LED_Referenced, 12);
lv_obj_set_height( ui_LED_Referenced, 12);
lv_obj_set_x( ui_LED_Referenced, 60 );
lv_obj_set_y( ui_LED_Referenced, 33 );
lv_obj_clear_flag( ui_LED_Referenced, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LED_Referenced, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Referenced, lv_color_hex(0x204127), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LED_Referenced, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LED_Referenced, lv_color_hex(0x877D7D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LED_Referenced, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Referenced, lv_color_hex(0x3BD620), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LED_Referenced, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LBL_Title_Sanity = lv_label_create(ui_Status_Panel);
lv_obj_set_width( ui_LBL_Title_Sanity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LBL_Title_Sanity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LBL_Title_Sanity, 0 );
lv_obj_set_y( ui_LBL_Title_Sanity, 67 );
lv_label_set_text(ui_LBL_Title_Sanity,"Sanity:");
lv_obj_set_style_text_font(ui_LBL_Title_Sanity, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LBL_Title_Sanity, lv_color_hex(0xE11515), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LBL_Title_Sanity, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_LED_Sanity = lv_obj_create(ui_Status_Panel);
lv_obj_set_width( ui_LED_Sanity, 12);
lv_obj_set_height( ui_LED_Sanity, 12);
lv_obj_set_x( ui_LED_Sanity, 60 );
lv_obj_set_y( ui_LED_Sanity, 67 );
lv_obj_clear_flag( ui_LED_Sanity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LED_Sanity, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Sanity, lv_color_hex(0x3BD620), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LED_Sanity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_LED_Sanity, lv_color_hex(0x877D7D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LED_Sanity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LED_Sanity, lv_color_hex(0x3BD620), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_LED_Sanity, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_BTN_Reset_Pos = lv_btn_create(ui_Status_Panel);
lv_obj_set_width( ui_BTN_Reset_Pos, 64);
lv_obj_set_height( ui_BTN_Reset_Pos, 23);
lv_obj_set_x( ui_BTN_Reset_Pos, 2 );
lv_obj_set_y( ui_BTN_Reset_Pos, 0 );
lv_obj_set_align( ui_BTN_Reset_Pos, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_BTN_Reset_Pos, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_Reset_Pos, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_Reset_Pos, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_Reset_Pos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Reset_Pos, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Reset_Pos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BTN_Reset_Pos, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_Reset_Pos, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Reset_Pos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_Reset_Pos, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_Reset_Pos, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_Reset_Pos, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Reset_Pos, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Reset_Pos, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Reset_Pos, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_BTN_Reset_Pos, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_BTN_Reset_Pos, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_BTN_Reset_Pos, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_BTN_LBL_Reset_pos = lv_label_create(ui_BTN_Reset_Pos);
lv_obj_set_width( ui_BTN_LBL_Reset_pos, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTN_LBL_Reset_pos, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BTN_LBL_Reset_pos, LV_ALIGN_CENTER );
lv_label_set_text(ui_BTN_LBL_Reset_pos,"Home pos.");
lv_obj_set_style_text_font(ui_BTN_LBL_Reset_pos, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTN_LBL_Reset_pos, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_BTN_LBL_Reset_pos, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_BTN_Reference = lv_btn_create(ui_Status_Panel);
lv_obj_set_width( ui_BTN_Reference, 64);
lv_obj_set_height( ui_BTN_Reference, 23);
lv_obj_set_x( ui_BTN_Reference, 2 );
lv_obj_set_y( ui_BTN_Reference, -5 );
lv_obj_set_align( ui_BTN_Reference, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BTN_Reference, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_Reference, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_Reference, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_Reference, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Reference, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Reference, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BTN_Reference, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_Reference, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Reference, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_Reference, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_Reference, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_Reference, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Reference, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Reference, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Reference, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_BTN_Reference, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_BTN_Reference, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_BTN_Reference, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_BTN_LBL_Reference = lv_label_create(ui_BTN_Reference);
lv_obj_set_width( ui_BTN_LBL_Reference, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTN_LBL_Reference, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BTN_LBL_Reference, LV_ALIGN_CENTER );
lv_label_set_text(ui_BTN_LBL_Reference,"Reference");
lv_obj_set_style_text_font(ui_BTN_LBL_Reference, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTN_LBL_Reference, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_BTN_LBL_Reference, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_BTN_Halt = lv_btn_create(ui_Status_Panel);
lv_obj_set_width( ui_BTN_Halt, 64);
lv_obj_set_height( ui_BTN_Halt, 23);
lv_obj_set_x( ui_BTN_Halt, 2 );
lv_obj_set_y( ui_BTN_Halt, 5 );
lv_obj_set_align( ui_BTN_Halt, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_BTN_Halt, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BTN_Halt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_Halt, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BTN_Halt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BTN_Halt, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Halt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_BTN_Halt, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_BTN_Halt, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Halt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BTN_Halt, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BTN_Halt, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BTN_Halt, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Halt, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Halt, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_BTN_Halt, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_BTN_Halt, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_BTN_Halt, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_BTN_Halt, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_BTN_LBL_Halt = lv_label_create(ui_BTN_Halt);
lv_obj_set_width( ui_BTN_LBL_Halt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BTN_LBL_Halt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BTN_LBL_Halt, LV_ALIGN_CENTER );
lv_label_set_text(ui_BTN_LBL_Halt,"Halt");
lv_obj_set_style_text_font(ui_BTN_LBL_Halt, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_BTN_LBL_Halt, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_BTN_LBL_Halt, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_On_BTN_Panel = lv_obj_create(ui_S2_Move);
lv_obj_set_width( ui_On_BTN_Panel, 35);
lv_obj_set_height( ui_On_BTN_Panel, 37);
lv_obj_set_x( ui_On_BTN_Panel, 3 );
lv_obj_set_y( ui_On_BTN_Panel, -54 );
lv_obj_set_align( ui_On_BTN_Panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_On_BTN_Panel, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_On_BTN_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_On_BTN_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_On_BTN_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_On_BTN_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Icon_Turn_ON = lv_img_create(ui_On_BTN_Panel);
lv_img_set_src(ui_BTN_Icon_Turn_ON, &ui_img_on_icon_png);
lv_obj_set_width( ui_BTN_Icon_Turn_ON, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_BTN_Icon_Turn_ON, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_BTN_Icon_Turn_ON, 1 );
lv_obj_set_y( ui_BTN_Icon_Turn_ON, -15 );
lv_obj_set_align( ui_BTN_Icon_Turn_ON, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_BTN_Icon_Turn_ON, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Icon_Turn_ON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_BTN_Icon_Turn_ON, lv_color_hex(0x00D2FF), LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_img_recolor_opa(ui_BTN_Icon_Turn_ON, 200, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_add_event_cb(ui_BTN_Menu_Scan_S2, ui_event_BTN_Menu_Scan_S2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Menu_Settings_S2, ui_event_BTN_Menu_Settings_S2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_BCK_GLOW, ui_event_BTN_BCK_GLOW, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_FWD_GLOW, ui_event_BTN_FWD_GLOW, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_LEFT_GLOW, ui_event_BTN_LEFT_GLOW, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_RIGHT_GLOW, ui_event_BTN_RIGHT_GLOW, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_UP_GLOW, ui_event_BTN_UP_GLOW, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_DOWN_GLOW, ui_event_BTN_DOWN_GLOW, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SLIDER_Step_Size, ui_event_SLIDER_Step_Size, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Reset_Pos, ui_event_BTN_Reset_Pos, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Reference, ui_event_BTN_Reference, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BTN_Halt, ui_event_BTN_Halt, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_On_BTN_Panel, ui_event_On_BTN_Panel, LV_EVENT_ALL, NULL);

}
